### ISSUE TITLE
感谢开源，motionhub数据集可以打包一下吗？文件太散不好下载

### ISSUE THREAD

**Issue by AIwem** [ZeyuLing/MotionLLaMA#1]
感谢开源，motionhub数据集可以打包一下吗？文件太散不好下载

**Comment by hengyuan-zhang-0** [comment]
+1

**Comment by ZeyuLing** [comment]
收到，马上处理

**Comment by ZeyuLing** [comment]
您好！我们更新了打包后的下载链接：https://pan.baidu.com/s/1vuewGrtVF9PjhEIiv153pw?pwd=AIXM 同时我们后续也会推出MotionHubV2，提供更精准的motion标注，欢迎关注！

> 感谢开源，motionhub数据集可以打包一下吗？文件太散不好下载
